### ISSUE TITLE
How do you get the Azure DevOps artifacts GUID?

### ISSUE THREAD

**Issue by Eilon** [AArnott/Library.Template#28]
There's this comment in the template:

https://github.com/AArnott/Library.Template/blob/4641b826b0717b388f241a7eeda281f344d7042a/azure-pipelines.yml#L18

But in Azure DevOps, how do I get the GUID? All I can seem to see is the feed name, something like `https://[AzureDevOpsProjectName].pkgs.visualstudio.com/_packaging/[MyPackageFeed]/nuget/v3/index.json`.

**Comment by AArnott** [comment]
You can get it by inserting a NuGet task into a YML file. Note how the `vstsFeed` parameter to the task discloses the GUID for the feed you picked from the dropdown list on the right-side panel:

![image](https://user-images.githubusercontent.com/3548/68918288-c7c7c380-072a-11ea-8c88-cc6ba07b7392.png)

Then you can copy the guid from there, discard the rest of the YAML changes, and paste it over this `ci_feed` placeholder value.

**Comment by Eilon** [comment]
Awesome, thanks for adding a link to this issue. This wasn't obvious at all.

**Comment by Eilon** [comment]
Turns out I was able to use the 'friendly' name of my CI feed and it worked fine:

```yml
variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  ci_feed: 'MyProjectName'
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
```

Indeed, when I go through Azure DevOps' UI, it does put in a GUID, but the 'friendly' name works fine, so I'll stick with that for now.
